### ISSUE TITLE
Add openssh-client to the SageMaker Distribution

### ISSUE THREAD

**Issue by giuseppeporcelli** [aws/sagemaker-distribution#117]
Add `openssh-client` to the SageMaker Distribution.
This is required when, for example, you are cloning a Git repository via SSH.

**Comment by athewsey** [comment]
Nice to see the linked #152 is merged, but I'm still not seeing this library yet in SMStudio?

Currently using LCConfig entries like the below to install it on-demand:

```sh
if ! command -v ssh &> /dev/null
then
    echo "ssh not found: Trying to sudo apt-get install openssh-client"
    sudo apt-get update && sudo apt-get -y install --no-install-recommends openssh-client
fi
```

(I found the initial `apt-get update` was needed for the install to work)

**Comment by claytonparnell** [comment]
There is some delay between open-source release, and release to Studio. openssh-client should now be available in both classic and new studio experiences
