### ISSUE TITLE
Don't use "apt-get" to install AWS CLI

### ISSUE THREAD

**Issue by balajisankar15** [aws/sagemaker-distribution#137]
The version of AWS CLI in apt-get is outdated. Please follow AWS public docs (https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to install AWS CLI in the sagemaker distribution image.

**Comment by claytonparnell** [comment]
Resolved by https://github.com/aws/sagemaker-distribution/pull/148
