### ISSUE TITLE
Allow docker-push to public ECR repositories

### ISSUE THREAD

**Issue by ketan-vijayvargiya** [aws/sagemaker-distribution#14]
Today, our script only allows pushing Docker images to private ECR repositories.

ECR's public gallery has a separate Boto3 client documented [here](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ecr-public.html). We should integrate that such that we are able to push to public repositories as well.

**Comment by balajisankar15** [comment]
Addressed this as part of https://github.com/aws/sagemaker-distribution/pull/19/

Pending Verification
