### ISSUE TITLE
Bug: Unable to find libdevice directory (${CUDA_DIR}/nvvm/libdevice) in GPU Images, Fix: Install cuda-nvcc to GPU images and update XLA_FLAGS

### ISSUE THREAD

**Issue by balajisankar15** [aws/sagemaker-distribution#15]
**Bug Description**:

While running Keras tests against the GPU Docker image, Tests were failing with the error - "Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice.

This issue has been discussed in several Github issues: 
One such Github issue: https://github.com/tensorflow/tensorflow/issues/58681

**How to fix it:**
* Install cuda-nvcc from nvidia channel
* After installation of cuda-nvcc, update XLA_FLAGS Environment variable to specify the Cuda Data Directory.
```export XLA_FLAGS=--xla_gpu_cuda_data_dir=/opt/conda```

**What is the impact:**

* Any sagemaker-distribution user might run into into the same issue while using the GPU images.

**Comment by erikinfo** [comment]
I agree on the impact. This should be looked on and fixed.

**Comment by erikinfo** [comment]
The libdevice file was indeed missing in the official Tensorflow 13.0 GPU optimized Image of Sagemaker and the problem can be resolved by typing this in the Terminal:

`!apt-get install cuda-compiler-11-8
`
In my case cuda 11.8 was already preinstalled by the image and setting the flags is necessary (export XLA_FLAGS=--xla_gpu_cuda_data_dir=/opt/conda). Installing the cuda-nvcc probably also resolves the problem, but cuda-compiler-11-8 is more lightweight and eventually does the same thing as outlined in the tensorflow issue you mentioned.

**Comment by aws-tianquaw** [comment]
cuda-nvcc has been added to SMD v2 GPU images: https://github.com/aws/sagemaker-distribution/blob/981276a7466779e820f522be3d6f844733bf1fe4/build_artifacts/v2/v2.0/v2.0.0/gpu.env.out#L643
