### ISSUE TITLE
When will this build with CUDA 12.0?

### ISSUE THREAD

**Issue by mariokostelac** [aws/sagemaker-distribution#151]
I see that new versions are still built with cuda 11.8. https://github.com/aws/sagemaker-distribution/blob/efe8692e39ab37b867e312fc0567a2a334ce06dc/src/config.py#L5 Do you have an estimate of when it's going to be built with the new cuda?

Installing any DL packages outside of the installed scope is becoming a pain because everything has to be pointed to `+cu118` packages, which is quite toilsome, especially for data scientists.

**Comment by ketan-vijayvargiya** [comment]
Thanks for your feedback, @mariokostelac.

This project aims to release a major version every 6 months. Given v1 was in Nov 2023, v2 should be in May-ish 2024. Also, moving from Cuda 11.x to 12 can only happen in a major version release of this project, so most likely that won't happen before May-ish 2024.

> Installing any DL packages outside of the installed scope is becoming a pain because everything has to be pointed to `+cu118` packages, which is quite toilsome, especially for data scientists.

I'd like to understand why this is so, though. As per our recommendation in the README, did you try something like this?

```
micromamba install ... --freeze-installed ...
```

Would that simplify some things for you?

**Comment by aws-tianquaw** [comment]
We've upgraded to CUDA 12.5 in SMD 2.x image releases: https://github.com/aws/sagemaker-distribution/blob/main/src/config.py#L57

**Comment by mariokostelac** [comment]
Thanks a lot!
