### ISSUE TITLE
Add a CLI editor program

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-distribution#164]
Today (in SageMaker Studio), it seems impossible to `git commit` (without a `-m` message) from the terminal in SageMaker Distribution with the following error:

```
error: cannot run editor: No such file or directory
error: unable to start editor 'editor'
```

The cause seems to be that there's no CLI editor program installed *at all* by default in SageMaker Distribution? No `emacs`, `nano`, `vim`, nothing.

I wouldn't get in to the whole emacs vs vim debate because honestly I *don't like* using CLI editors so don't really care... but IMO there should really be *something* just so that `git commit` works out of the box?

**Comment by just4brown** [comment]
Will be adding nano to the runtime in the v1.5.0 release
