### ISSUE TITLE
Pull latest sagemaker-python-sdk to fix get_caller_identity

### ISSUE THREAD

**Issue by claytonparnell** [aws/sagemaker-distribution#168]
When using sagemaker-distribution in private spaces on SageMaker Studio, get_caller_identity is unable to fetch execution role, which breaks functionality for any notebooks or functionality which use this method. This is fixed in https://github.com/aws/sagemaker-python-sdk/pull/4388/files, part of release 2.205.0. Include this version in next minor release.

**Comment by just4brown** [comment]
sagemaker-python-sdk 2.205 requires a minimum boto3 version of [1.33.3](https://github.com/conda-forge/sagemaker-python-sdk-feedstock/commit/781e3532656105e4b704cf5484362f98516b88f3). sagemaker-distribution is stuck at 1.28.64 and currently blocked from meeting that requirement until https://github.com/aws/sagemaker-distribution/issues/167 is fixed

**Comment by just4brown** [comment]
Pushing this fix out of v1.5.0 release. Need to postpone until blocking issue is resolved.
