### ISSUE TITLE
when will this build with torch 2.1 (or 2.2)?

### ISSUE THREAD

**Issue by laphang** [aws/sagemaker-distribution#169]
I noticed that it's still using torch 2.0. 
https://github.com/aws/sagemaker-distribution/blob/main/build_artifacts/v1/v1.4/v1.4.2/gpu.env.out

When can we expect a build with torch 2.1 (or 2.2 that just got released)?

**Comment by claytonparnell** [comment]
Will aim for v2 major release to include upgrade of torch

**Comment by claytonparnell** [comment]
After some investigation, we are blocked on this until autogluon ups their torch upperbound, currently set to 2.0. There's an issue tracking this issue here https://github.com/autogluon/autogluon/issues/3613 with milestone of autogluon 1.1.

**Comment by FireballDWF** [comment]
autogluon v1.1 has released, includes the torch 2.1 support.

**Comment by laphang** [comment]
Thanks!
