### ISSUE TITLE
cron service not running on SM Distribution 1.6.0

### ISSUE THREAD

**Issue by giuseppeporcelli** [aws/sagemaker-distribution#354]
SM Distribution 1.6.0 includes `cron`, but the service is not running.

```
sagemaker-user@default:~$ service cron status
 * cron is not running
```

**Comment by athewsey** [comment]
It's been a while since this was raised - can anybody confirm if it's still true now on v1.9?

**Comment by aws-tianquaw** [comment]
Hi @athewsey, @giuseppeporcelli, It looks like cron service will not start running automatically. To enable and use it, you may run `sudo service cron start` inside your container. I've verified that for v1.10 image, the cron service is running after executing that command.

```
(base) sagemaker-user@e20471487fe0:~$ sudo service cron start
 * Starting periodic command scheduler cron
 (base) sagemaker-user@e20471487fe0:~$ service cron status
 * cron is running
```

**Comment by aws-tianquaw** [comment]
Looks like the sample script already added this workaround: https://github.com/aws-samples/sagemaker-studio-apps-lifecycle-config-examples/commit/15f74e903691bba46997371a2e952e63a7c363d2
