### ISSUE TITLE
Missing dependency for AWS CLI help commands

### ISSUE THREAD

**Issue by SeijiSuenaga** [aws/sagemaker-distribution#379]
AWS CLI is pre-installed in the image, but its help commands such as `aws help` currently fail with this message:

> Could not find executable named "groff or mandoc"

Would it be possible to also pre-install the dependencies that the help commands require?

**Comment by claytonparnell** [comment]
Hello, we added mandoc [here](https://github.com/aws/sagemaker-distribution/pull/355) to resolve this issue, and it's available for versions 1.7+. Can you confirm which version you see this issue on?

**Comment by claytonparnell** [comment]
No problem, closing this as resolved.
