### ISSUE TITLE
Still Beta?

### ISSUE THREAD

**Issue by AIByteSmith** [aws/sagemaker-distribution#38]
Does the Beta notice in the README still apply? This seems to be public now and no longer relevant.

**Comment by ketan-vijayvargiya** [comment]
We still consider this a "beta" project where we'd like to collect community feedback before marking it ready-for-production-use.

If you have any feedback after using the Docker images, please reach out.

**Comment by AIByteSmith** [comment]
Wondering if this still applies: "Beta Service is confidential and you may not discuss the features, functionality, or documentation related to the Beta Service with any parties that are not authorized by AWS"
