### ISSUE TITLE
Generate a table of package dependencies

### ISSUE THREAD

**Issue by ketan-vijayvargiya** [aws/sagemaker-distribution#4]
As part of the `build` command, we generate couple of _env.out_ files which contain detailed information about all the packages in the package closure.

We should also generate a new file which contains the same information but in a more human-consumable way. For example:

- The new file could consolidate version numbers etc., per package, across CPU and GPU variants. That way, users don't have to tally multiple files to know which version of, say, PyTorch is present in CPU and GPU variants.
- We can present the data in tabular format.

**Comment by balajisankar15** [comment]
If a single system is going to be always responsible for generating the images for all the variants (CPU/GPU/others), then this (generate a single table in which you can compare versions) is possible to implement.

But if we end up using different compute(type of instance) for generating different image types, then this can't be generated as part of the 'build' command. 

May be we can create a separate command for generating release notes (That command needs to be ran after all the image variants are built.
