### ISSUE TITLE
Include git please

### ISSUE THREAD

**Issue by mulka** [aws/sagemaker-distribution#42]

**Comment by ketan-vijayvargiya** [comment]
Hi, appreciate if you could add some details of your use case. (For example, how you intend to use the Docker images and how git will help.)

**Comment by mulka** [comment]
Sure, I want to use this in SageMaker Studio and be able to git clone open source models from GitHub and HuggingFace

**Comment by ellisonbg** [comment]
Yep, definitely need git :-)

**Comment by balajisankar15** [comment]
Git is part of our 0.5.0 release . Thanks @just4brown for releasing 0.5.0
