### ISSUE TITLE
[BUG] Incorrect TensorFlow Version in SMD 1.8 GPU

### ISSUE THREAD

**Issue by hugowong-aws** [aws/sagemaker-distribution#438]
### Category

Compatibility Issue

### 🐛 Describe the bug

# Summary
: SMD 1.8.0+ has TensorFlow CPU installed instead of GPU

## Replication steps
1. SageMaker Studio: Create JupyterLab private or shared space, use GPU instance type and above mentioned image and version.
2. Running the follow command for TensorFlow will show that there is no visible GPU devices
```
import tensorflow as tf
tf.config.list_physical_devices('GPU')

[]
```
3. pytorch will correctly show that CUDA is enabled.
4. running `$conda list | grep tensorflow` will show cpu build is installed

### 🐛 Describe the expected behavior

1. TensorFlow should list any GPU device passed to the container.
2. TensorFlow should be able to execute code using the GPU device.

### Image Tags

1.8.0-gpu

**Comment by claytonparnell** [comment]
Fixed in v1.9
