### ISSUE TITLE
Update Code Editor extensions

### ISSUE THREAD

**Issue by SeijiSuenaga** [aws/sagemaker-distribution#477]
The Code Editor extensions included in SMD [2.0.0](https://github.com/aws/sagemaker-distribution/blob/main/build_artifacts/v2/v2.0/v2.0.0/dirs/etc/code-editor/extensions.txt) (the latest version available in SageMaker Studio right now) are significantly outdated:

- Jupyter [2023.9.100](https://open-vsx.org/extension/ms-toolsai/jupyter/2023.9.100) is from 2023-09-11
- Python [2023.20.0](https://open-vsx.org/extension/ms-python/python/2023.20.0) is from 2023-11-01
- AWS Toolkit [1.99.0](https://open-vsx.org/extension/amazonwebservices/aws-toolkit-vscode/1.99.0) is from 2023-11-19
  - Also, version [3.2.0](https://open-vsx.org/extension/amazonwebservices/aws-toolkit-vscode/3.2.0) from 2024-05-07 moved CodeWhisperer to the [Amazon Q](https://open-vsx.org/extension/amazonwebservices/amazon-q-vscode) extension

### Alternatives

My environment doesn't allow access to open-vsx.org so I'm not sure if manually updating the extensions within Code Editor would normally work.

I can make newer VSIX files available privately, e.g. in S3, and install them at startup with a lifecycle config script, but I found that the installs took a long time, which made startup fail because the lifecycle script times out after 5 minutes.

Edit: Turns out my extension installs were taking a long time mainly due to unnecessary network requests to open-vsx.org, which isn't accessible in my VPC. The requests wait a couple minutes before timing out, but I can make them fail fast by routing them straight to localhost in `/etc/hosts`, which makes my installs take less than 10 seconds total. So this is a pretty viable workaround for now.

**Comment by aws-tianquaw** [comment]
Hi @SeijiSuenaga, Thanks for raising the issue. We are working on investigating and updating the CodeEditor extensions. I'll provide ETA once it becomes available.

**Comment by arkaprava08** [comment]
@SeijiSuenaga Till we update the SMD;  Another recommendation would be to create a custom image for code editor and use our BYOI feature. You can update the image locally and then upload to SM to use the the updated extension.

**Comment by claytonparnell** [comment]
Updated jupyter, python in https://github.com/aws/sagemaker-distribution/pull/502/files
Updated aws-toolkit in https://github.com/aws/sagemaker-distribution/pull/507/files

Resolving this issue for now, feel free to re-open if you have any other concerns. Thanks for using SMD!
