### ISSUE TITLE
Ensure that integration tests don't change the underlying environment

### ISSUE THREAD

**Issue by ketan-vijayvargiya** [aws/sagemaker-distribution#5]
Today, _test_dockerfile_based_harness.py_ runs a bunch of integration tests against the images we build before those images are published to ECR. 

As part of those tests, we may install a few dependencies via `micromamba` or `pip`. And that _may_ modify the underlying package closure against which the tests run. So, after the tests run, we should assert that the original package closure hasn't changed in the _test image_ (though new dependencies, that come through the test, are okay).

**Comment by ketan-vijayvargiya** [comment]
We may not have to do this if we used the `--freeze-installed` parameter to `micromamba install` test dependencies.

**Comment by balajisankar15** [comment]
Fixed as part of https://github.com/aws/sagemaker-distribution/pull/39
