### ISSUE TITLE
Unable to build the v2.1.0 image 

### ISSUE THREAD

**Issue by j0bekt01** [aws/sagemaker-distribution#512]
### Category

BUG

### 🐛 Describe the bug

I am trying to recreate the image specified in the v2.1.0 Dockerfile, but it fails at the end with the following message: `/home/sagemaker-user/licenses/LINUX_PACKAGES_LICENSES doesn't exist, which is needed for license attribution compliance`. I checked the contents of the [zip file](https://aws-dlinfra-utilities.s3.amazonaws.com/oss_compliance.zip) and confirmed that the path is not included.

### 🐛 Describe the expected behavior

the image should build without issues.

### Image Tags

![image](https://github.com/user-attachments/assets/745ebdac-f898-4434-9340-6709a4ec67f1)

**Comment by claytonparnell** [comment]
Can you confirm the command you're using to build the image?
I've locally tested `python ./src/main.py build --target-patch-version 2.1.0 --skip-tests` and it works successfully

**Comment by j0bekt01** [comment]
I was using the docker build on the Docker file, I didn't use the main.py

**Comment by j0bekt01** [comment]
following @claytonparnell instructions worked as expected.
