### ISSUE TITLE
Python 3.8?

### ISSUE THREAD

**Issue by tcmaps** [aws/sagemaker-distribution#63]
Any reason it's fixed on that old version?

Sagemaker Lab uses 3.9 already, switching to distribution as environment wasn't straightforward.

**Comment by balajisankar15** [comment]
We are currently testing python 3.10 upgrade. It is currently in beta. We don't have an estimated release date, but in the mean time you can try our beta.

Check : 
* public.ecr.aws/sagemaker/sagemaker-distribution:1.0.0-beta-cpu
* public.ecr.aws/sagemaker/sagemaker-distribution:1.0.0-beta-gpu
* https://github.com/aws/sagemaker-distribution/commit/d4530252760c5666a161dbd0bf14edd0969d602d
