### ISSUE TITLE
aiobotocore dependency on old version of botocore causes dependency conflicts

### ISSUE THREAD

**Issue by andrii-i** [aws/sagemaker-distribution#83]
### Problem

Sagemaker-distribution will likely have multiple packages that (transitively) depend on `aiobotocore`.`aiobotocore` dependency on old version of `botocore` (1.31.17) causes dependency conflict with packages that depend on newer version of `botocore`. For example, because of this latest versions of `s3fs` and `boto3`  packages conflict (new versions of `boto3` depend on `botocore >=1.31.35,<1.32.0` and up).

### Potential solution

Bump `botocore` to latest version in `aiobotocore` repository: https://github.com/aio-libs/aiobotocore/issues/1043.

**Comment by aws-tianquaw** [comment]
Looks like [the aiobotocore PR ](https://github.com/aio-libs/aiobotocore/pull/1037)has been merged, closing the issue
