### ISSUE TITLE
Add documentation on contribution process

### ISSUE THREAD

**Issue by dlqqq** [aws/sagemaker-distribution#95]
There is minimal documentation on the contribution process and the expected responsibilities of a contributor. This should be present in `CONTRIBUTING.md`.

**Comment by aws-tianquaw** [comment]
The detailed contribution process and the expected responsibilities of a contributor are now in updated `CONTRIBUTING.md`: https://github.com/aws/sagemaker-distribution/blob/main/CONTRIBUTING.md
