### ISSUE TITLE
Error when running JupyterLab on 1.0.0-beta

### ISSUE THREAD

**Issue by dlqqq** [aws/sagemaker-distribution#98]
I'm seeing an error when running JupyterLab on the 1.0.0-beta container:

```
$ jupyter lab
[E 2023-10-19 19:12:48.722 ServerApp] Exception while loading config file /etc/jupyter/jupyter_server_config.py
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.10/site-packages/traitlets/config/application.py", line 915, in _load_config_files
        config = loader.load_config()
      File "/opt/conda/lib/python3.10/site-packages/traitlets/config/loader.py", line 627, in load_config
        self._read_file_as_dict()
      File "/opt/conda/lib/python3.10/site-packages/traitlets/config/loader.py", line 660, in _read_file_as_dict
        exec(compile(f.read(), conf_filename, "exec"), namespace, namespace)  # noqa
      File "/etc/jupyter/jupyter_server_config.py", line 4, in <module>
        from nb_conda_kernels import CondaKernelSpecManager
    ModuleNotFoundError: No module named 'nb_conda_kernels'
...
```

The server is still able to start, and extensions still appear to be getting loaded & initialized correctly.

I believe this error is due to changes to the default JL config in https://github.com/aws/sagemaker-distribution/pull/76. The default Conda base environment in the image does not have `nb_conda_kernels` installed. It's also unclear how this dependency is being used, and whether it should be used at all, given that [the package has not been updated in nearly 3 years](https://github.com/Anaconda-Platform/nb_conda_kernels).

**Comment by ketan-vijayvargiya** [comment]
@dlqqq @zuoyuanh - Is this issue still relevant? Or is it already fixed?

**Comment by claytonparnell** [comment]
Irrelevant nb_conda_kernels import was removed in https://github.com/aws/sagemaker-distribution/pull/125/. Going to go ahead and close this as it's been resolved.
